name: deploy
on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform # All .tf files are in the 'terraform' directory
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::981026211833:role/github-actions-purrimeter
          aws-region: ca-central-1

      - name: Log in to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        id: build
        working-directory: . # This needs to run from the root and not 'terraform'
        env:
          REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          REPO: purrimeter-fetch
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t $REGISTRY/$REPO:$IMAGE_TAG lambdas/fetch
          docker push $REGISTRY/$REPO:$IMAGE_TAG
          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $REGISTRY/$REPO:$IMAGE_TAG)
          echo "image_uri=$DIGEST" >> "$GITHUB_OUTPUT"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color -var="image_uri=${{ steps.build.outputs.image_uri }}"

      - name: Debug image URI
        run: echo "image_uri is >>>${{ steps.build.outputs.image_uri }}<<<"

      - name: Terraform Apply
        run: terraform apply -auto-approve -no-color -var="image_uri=${{ steps.build.outputs.image_uri }}"
